# Generated by Django 5.1.6 on 2025-03-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_alt_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(help_text='Enter the UPI ID for payments', max_length=100, unique=True)),
            ],
        ),
    ]
