# Generated by Django 5.1.6 on 2025-03-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_upi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UPI',
        ),
    ]
