# Generated by Django 5.1.6 on 2025-03-08 17:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_upi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='category_images'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_images'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='qr_codes'),
        ),
    ]
